# Generated by Django 5.1.3 on 2025-07-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestLog',
        ),
    ]
